export const dynamic = "force-dynamic";
import Link from "next/link";
import PrintButton from "@/components/PrintButton";
import { getReportData } from "@/lib/serverData";

export default async function ReviewPage({ params }: { params: Promise<{ attemptId: string }> }) {
  const { attemptId } = await params;
  const data = await getReportData(attemptId);
  if (!data) return <div className="card p-8 text-center">Report not found</div>;
  const { attempt, questions, answers } = data;
  const map = new Map(answers.map((a:any)=>[String(a.questionId), a]));
  return <div className="space-y-6"><div className="card gradient p-6"><p className="text-sm font-medium text-muted">Result Review</p><p className="mt-1 text-base font-medium">{attempt.testTitle}</p><div className="mt-5 grid gap-3 md:grid-cols-5"><div className="mini-card p-4"><b>{attempt.score}</b><p className="text-xs text-muted">Score</p></div><div className="mini-card p-4"><b>{attempt.accuracy}%</b><p className="text-xs text-muted">Accuracy</p></div><div className="mini-card p-4"><b>{attempt.correct}</b><p className="text-xs text-muted">Correct</p></div><div className="mini-card p-4"><b>{attempt.wrong}</b><p className="text-xs text-muted">Wrong</p></div><div className="mini-card p-4"><b>{attempt.elapsedSeconds}s</b><p className="text-xs text-muted">Time</p></div></div><div className="no-print mt-5 flex flex-wrap gap-3"><Link href="/dashboard" className="rounded-xl border px-4 py-2 font-medium" style={{borderColor:'var(--border)'}}>Dashboard</Link><a href={`/api/export/${attemptId}/excel`} className="rounded-xl bg-emerald-600 px-4 py-2 font-medium text-white">Export Excel</a><PrintButton /></div><p className="no-print mt-2 text-sm text-muted">For PDF: press Ctrl+P and save as PDF from this review page.</p></div><div className="space-y-4 print-report">{questions.map((q:any)=>{const a:any=map.get(String(q._id)); const attempted=!!a?.selectedOption; const correct=a?.isCorrect; return <div key={q._id} className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><p className="font-medium">{q.order}. {q.question}</p><span className="rounded-full px-3 py-1 text-xs font-medium" style={{background: correct?'#dcfce7': attempted?'#fee2e2':'#e2e8f0',color: correct?'#166534':attempted?'#991b1b':'#475569'}}>{correct?'Correct':attempted?'Wrong':'Not Attempted'}</span></div><div className="mt-3 grid gap-2 md:grid-cols-2">{(['A','B','C','D'] as const).map(k=><p key={k} className="rounded-xl border p-3 text-sm" style={{borderColor: q.answer===k?'#16a34a':a?.selectedOption===k?'#dc2626':'var(--border)', background:q.answer===k?'rgba(22,163,74,.08)':a?.selectedOption===k?'rgba(220,38,38,.08)':'transparent'}}><b>{k}.</b> {q.options[k]}</p>)}</div><p className="mt-3 text-sm text-muted"><b>Explanation:</b> {q.explanation}</p><p className="mt-2 text-xs text-muted">{q.subject} / {q.chapter} / {q.topic} • Time: {a?.timeSpentSeconds || 0}s</p></div>})}</div></div>;
}
